### ISSUE TITLE
Thank you for your excellent work. Could you provide more details about the configuration environment? What CUDA version are you using?

### ISSUE THREAD

**Issue by hash-wls** [JiaruiFeng/KP-GNN#4]

**Comment by JiaruiFeng** [comment]
Hi,

Thanks for the interest in our work. My CUDA version for running the experiments is 11.7. However, I believe the CUDA version is more related to the specific GPU you are using instead of the code base. Maybe you can provide me with more information about the problem you are facing so I can better help you figure it out.

Best,
Jiarui

**Comment by hash-wls** [comment]
Thank you, the issue I encountered is the inability to install PyG. I couldn't find a PyG version compatible with CUDA corresponding to torch 1.11.0.
